dist: trusty
language: node_js
node_js:
  - "7"
script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
    - yarn global add @angular/cli
    - yarn global add typings
    - yarn global add firebase-tools
    - yarn install
after_success:
    - ng build -prod --aot
    - firebase deploy --token "$FIREBASE_TOKEN"



