sudo: false
dist: trusty
language: node_js
node_js:
  - "7"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_install:
  - sudo apt install -y gzip
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn global add @angular/cli
  - yarn global add typings
  - yarn global add firebase-tools
  - yarn install

script:
  - ng build --prod --aot
  - cd dist gzip -k -r * && cd ..

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN