# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g @angular/cli
      - run: ng build --prod --stats-json
      - run: npm run scully -- --scanRoutes

      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: kerron-gordon
          TARGET_BRANCH: master
       
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          repo: kerrongordon/kerrongordon.github.io
          target_branch: master
          build_dir: ./dist/static/
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
